version: '3'
services:
  webapp:
    build: .
    container_name: online-store
    
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file: .env
    ports:
      - "8000:8000"
